services:

  mariadb:
    image: mariadb:11
    container_name: chesshub-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: chesshub
      MYSQL_USER: chesshub
      MYSQL_PASSWORD: chesshub1234
    ports:
      - "3307:3306"
    volumes:
      - chesshub-db-data:/var/lib/mysql
      - ./database/chesshub_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - chesshub-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: chesshub-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: chesshub
      PMA_PASSWORD: chesshub1234
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - chesshub-net

volumes:
  chesshub-db-data:

networks:
  chesshub-net:
    driver: bridge
