apiVersion: v1
kind: Secret
metadata:
  name: chesshub-secrets
  namespace: grup4
type: Opaque
stringData:
  db-root-password: CHANGE_ME
  db-password: CHANGE_ME
  jwt-secret: CHANGE_ME_use_a_long_random_string
  smtp-user: CHANGE_ME_email@gmail.com
  smtp-pass: CHANGE_ME_16_char_app_password
